[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x238a5a4c57beaf2ed5620512135a4bc8e022cd2d13ae7f2cb13c3f392943676"
transaction_hash = "0x5125d354079edf077582c91f6fa718e0e5823b5f0a88bde084343e1f04948b9"
block_number = 3
seed = "starkludo"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x72177d869ea3f7ef65ffa20dd6a1fb5e8bcea6ab1e9e622dcf2786b5a12f54b"
class_hash = "0x455c9caaec12f3dd89460db1c8a467540ca9deb0c7f5fe6e132242fc61524ab"
original_class_hash = "0x455c9caaec12f3dd89460db1c8a467540ca9deb0c7f5fe6e132242fc61524ab"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/starkludo-GameActions-72b46dc4.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-GameActions"
systems = [
    "restart",
    "terminate_game",
    "invite_player",
    "join_game",
]
manifest_name = "starkludo-GameActions-72b46dc4"

[[contracts]]
kind = "DojoContract"
address = "0x32b88171586f2ecd60f67bee1f3f96a0da55a7a6ab29bfce31ecd57e9d97291"
class_hash = "0x58f4263a51e5bcb416c0778f52fde01024c12ddf2701389b229ff081997952c"
original_class_hash = "0x58f4263a51e5bcb416c0778f52fde01024c12ddf2701389b229ff081997952c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/starkludo-PlayerActions-20dad3ac.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-PlayerActions"
systems = [
    "create",
    "update_username",
]
manifest_name = "starkludo-PlayerActions-20dad3ac"

[[models]]
kind = "DojoModel"
class_hash = "0x39fa438bf58ecd4698515fa196c9f617f80896de6c92eeeffadeabe39347936"
original_class_hash = "0x39fa438bf58ecd4698515fa196c9f617f80896de6c92eeeffadeabe39347936"
abi = "manifests/dev/deployment/abis/models/starkludo-Game-5286f583.json"
tag = "starkludo-Game"
qualified_path = "starkludo::models::game::game"
manifest_name = "starkludo-Game-5286f583"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "created_by"
type = "ContractAddress"
key = false

[[models.members]]
name = "game_status"
type = "GameStatus"
key = false

[[models.members]]
name = "game_mode"
type = "GameMode"
key = false

[[models.members]]
name = "player_green"
type = "felt252"
key = false

[[models.members]]
name = "player_yellow"
type = "felt252"
key = false

[[models.members]]
name = "player_blue"
type = "felt252"
key = false

[[models.members]]
name = "player_red"
type = "felt252"
key = false

[[models.members]]
name = "invited_players"
type = "Array<felt252>"
key = false

[[models.members]]
name = "winner_1"
type = "felt252"
key = false

[[models.members]]
name = "winner_2"
type = "felt252"
key = false

[[models.members]]
name = "winner_3"
type = "felt252"
key = false

[[models.members]]
name = "next_player"
type = "felt252"
key = false

[[models.members]]
name = "number_of_players"
type = "u8"
key = false

[[models.members]]
name = "rolls_count"
type = "u256"
key = false

[[models.members]]
name = "rolls_times"
type = "u256"
key = false

[[models.members]]
name = "dice_face"
type = "u8"
key = false

[[models.members]]
name = "player_chance"
type = "ContractAddress"
key = false

[[models.members]]
name = "has_thrown_dice"
type = "bool"
key = false

[[models.members]]
name = "b0"
type = "felt252"
key = false

[[models.members]]
name = "b1"
type = "felt252"
key = false

[[models.members]]
name = "b2"
type = "felt252"
key = false

[[models.members]]
name = "b3"
type = "felt252"
key = false

[[models.members]]
name = "g0"
type = "felt252"
key = false

[[models.members]]
name = "g1"
type = "felt252"
key = false

[[models.members]]
name = "g2"
type = "felt252"
key = false

[[models.members]]
name = "g3"
type = "felt252"
key = false

[[models.members]]
name = "r0"
type = "felt252"
key = false

[[models.members]]
name = "r1"
type = "felt252"
key = false

[[models.members]]
name = "r2"
type = "felt252"
key = false

[[models.members]]
name = "r3"
type = "felt252"
key = false

[[models.members]]
name = "y0"
type = "felt252"
key = false

[[models.members]]
name = "y1"
type = "felt252"
key = false

[[models.members]]
name = "y2"
type = "felt252"
key = false

[[models.members]]
name = "y3"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x552147f9afe3a1587cf334876dd5e9b5b52200aabf22a0d7cd036625580b6c2"
original_class_hash = "0x552147f9afe3a1587cf334876dd5e9b5b52200aabf22a0d7cd036625580b6c2"
abi = "manifests/dev/deployment/abis/models/starkludo-Player-3bb81cb1.json"
tag = "starkludo-Player"
qualified_path = "starkludo::models::player::player"
manifest_name = "starkludo-Player-3bb81cb1"

[[models.members]]
name = "username"
type = "felt252"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "total_games_played"
type = "u256"
key = false

[[models.members]]
name = "total_games_won"
type = "u256"
key = false
