kind = "DojoModel"
class_hash = "0x4981fc3afd0b7d772d3902740a8e405159ae4e796b96fbd3354e1ac12c43d6a"
original_class_hash = "0x4981fc3afd0b7d772d3902740a8e405159ae4e796b96fbd3354e1ac12c43d6a"
abi = "manifests/dev/base/abis/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
