kind = "DojoModel"
class_hash = "0x3d21dd0b895cae94a3f24aeeafc66deeaddb910800828cbfc9d0c4407f62609"
original_class_hash = "0x3d21dd0b895cae94a3f24aeeafc66deeaddb910800828cbfc9d0c4407f62609"
abi = "manifests/dev/base/abis/models/dojo_starter-Position-2ac8b4c1.json"
tag = "dojo_starter-Position"
manifest_name = "dojo_starter-Position-2ac8b4c1"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
