kind = "DojoModel"
class_hash = "0x26f6acac127b824d05c1e1e7162bc1c800fe179e2d9195aac67ed87bef87a2d"
original_class_hash = "0x26f6acac127b824d05c1e1e7162bc1c800fe179e2d9195aac67ed87bef87a2d"
abi = "manifests/dev/base/abis/models/starkludo-Position-3a0db170.json"
tag = "starkludo-Position"
manifest_name = "starkludo-Position-3a0db170"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
