kind = "DojoContract"
class_hash = "0x3e8d55d593fccedc0eba028ace6897a45aad4486cd7888e0281b94931f692a8"
original_class_hash = "0x3e8d55d593fccedc0eba028ace6897a45aad4486cd7888e0281b94931f692a8"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/starkludo-GameActions-72b46dc4.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-GameActions"
manifest_name = "starkludo-GameActions-72b46dc4"
